export interface TechStack {
  slug: string;
  name: string;
  category: string;
  description: string;
  integration: string;
  faqs: { q: string; a: string }[];
}

export const techStacks: TechStack[] = [
  {
    slug: "python",
    name: "Python AI Ecosystem",
    category: "Machine Learning & Data Science",
    description: "Enterprise-grade predictive models built on Python's robust data science ecosystem, including PyTorch, TensorFlow, and scikit-learn.",
    integration: "We integrate Python-based predictive engines seamlessly into your existing software infrastructure via secure REST APIs and microservices.",
    faqs: [
      { q: "Why use Python for predictive AI?", a: "Python is the industry standard for machine learning and predictive analytics. Its extensive ecosystem of libraries (like PyTorch and scikit-learn) allows us to build highly accurate, production-ready predictive models faster and more reliably than other languages." },
      { q: "Can Python AI models integrate with our existing software?", a: "Yes. We wrap our Python predictive engines in secure, high-performance APIs (typically using FastAPI or FastAPI) that can be called by any modern software application, regardless of what language your existing system is built in." },
      { q: "How do you ensure Python models perform at scale?", a: "We deploy Python models using containerised microservices architecture on scalable cloud infrastructure, ensuring they can handle high-throughput, real-time prediction requests without latency." }
    ]
  },
  {
    slug: "aws",
    name: "AWS Cloud Infrastructure",
    category: "Cloud Infrastructure",
    description: "Highly scalable, secure cloud architecture built on Amazon Web Services to power real-time predictive intelligence at enterprise scale.",
    integration: "We leverage AWS services like SageMaker, Lambda, and Redshift to build secure, highly available predictive pipelines that scale automatically with your business needs.",
    faqs: [
      { q: "Is AWS secure for sensitive operational data?", a: "Yes. AWS provides enterprise-grade security, compliance, and data sovereignty controls. We architect our solutions using AWS best practices, ensuring your data is encrypted at rest and in transit, with strict IAM access controls." },
      { q: "How does AWS support predictive AI?", a: "AWS offers purpose-built machine learning infrastructure like Amazon SageMaker, which allows us to train, deploy, and scale predictive models efficiently. Combined with serverless compute (AWS Lambda), we deliver real-time predictions without the overhead of managing servers." },
      { q: "Can you deploy predictive models on our existing AWS account?", a: "Absolutely. We can architect and deploy the predictive intelligence layer directly within your existing AWS environment, ensuring it complies with your internal IT governance and security policies." }
    ]
  },
  {
    slug: "react-nextjs",
    name: "React & Next.js",
    category: "Frontend Architecture",
    description: "High-performance, dynamic user interfaces built with React and Next.js that surface predictive insights in real time.",
    integration: "We build intuitive, responsive dashboards and web applications that consume predictive APIs and present complex data as actionable, human-readable insights.",
    faqs: [
      { q: "Why use Next.js for AI applications?", a: "Next.js provides server-side rendering and static site generation, ensuring that complex AI-driven web applications load instantly. It's the ideal framework for building fast, secure, and SEO-friendly platforms that surface predictive insights." },
      { q: "How do React interfaces handle real-time predictive data?", a: "React's component-based architecture is perfectly suited for dynamic data. We use modern state management and real-time data fetching to update the UI instantly as new predictive signals are generated by the AI engine." },
      { q: "Are Next.js applications scalable?", a: "Yes. Next.js applications deployed on modern edge networks can scale infinitely to handle millions of users globally, with zero configuration required for load balancing." }
    ]
  },
  {
    slug: "node-js",
    name: "Node.js & TypeScript",
    category: "Backend Architecture",
    description: "Fast, scalable backend services built with Node.js and TypeScript to orchestrate data flow between your systems and our predictive models.",
    integration: "We use TypeScript to ensure type safety and reliability across the stack, building robust API gateways that handle data ingestion, authentication, and prediction routing.",
    faqs: [
      { q: "Why use TypeScript for enterprise software?", a: "TypeScript adds static typing to JavaScript, catching errors at compile time rather than runtime. This drastically reduces bugs in production and makes large-scale codebases easier to maintain and extend over time." },
      { q: "How does Node.js handle heavy AI workloads?", a: "While Node.js handles the API routing, authentication, and data orchestration, the heavy machine learning workloads are offloaded to dedicated Python microservices. Node.js excels at managing thousands of concurrent connections asynchronously." },
      { q: "Can Node.js integrate with legacy databases?", a: "Yes. Node.js has an extensive ecosystem of drivers and ORMs that allow it to connect securely to virtually any database, from modern NoSQL stores to legacy SQL systems." }
    ]
  },
  {
    slug: "snowflake-dbt",
    name: "Snowflake & dbt",
    category: "Data Engineering",
    description: "Modern data stack architecture for ingesting, transforming, and preparing enterprise data for predictive machine learning models.",
    integration: "We build automated data pipelines that extract data from your silos, transform it using dbt, and load it into Snowflake for high-performance model training and inference.",
    faqs: [
      { q: "Why do we need a data warehouse for predictive AI?", a: "Predictive models require clean, structured, and historical data to identify patterns. A modern data warehouse like Snowflake centralises your siloed data, providing a single source of truth for the AI models to learn from." },
      { q: "What is dbt and why is it important?", a: "dbt (data build tool) allows us to transform raw data in your warehouse into clean, reliable datasets ready for machine learning. It applies software engineering best practices — like version control and testing — to your data pipelines." },
      { q: "Can Snowflake handle real-time predictive queries?", a: "Snowflake is excellent for model training and batch predictions. For millisecond real-time inference, we typically cache the transformed features in an operational database or feature store closer to the application layer." }
    ]
  }
];
